# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-17 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, validators=[store.models.nameValidation], verbose_name='Product name')),
                ('price', models.IntegerField(validators=[store.models.priceValidation], verbose_name='Price (bits)')),
                ('description', models.CharField(max_length=255, validators=[store.models.descValidation])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
